version: '2.1'

services:

  notifications-ms:
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3002:3000
    depends_on:
      - notifications-db

  notifications-db:
    build: .
    ports:
      - "27017:27017"
