version: '2.1'

services:
  notifications-ms:
    container_name: notifications-ms
    image: notifier
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - notifications-db
  notifications-db:
    container_name: notifications-db
    image: mongo
    ports:
      - "27017:27017"
